services:
  frontend:
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes: 
      - type: bind
        source: ./frontend
        target: /home/node
      - type: volume
        target: /home/node/node_modules
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - frontend
      