services:
  frontend:
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes: 
      - type: bind
        source: ./frontend
        target: /home/node
      - type: volume
        target: /home/node/node_modules
  backend:
    stdin_open: true
    tty: true
    ports:
      - "8080:80"
    build:
      dockerfile: Dockerfile.dev
      context: ./backend